[package]
name = "services"
version = "0.1.0"
edition = "2021"

[dependencies]
http = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
colored = { workspace = true }